### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tamjid1971** [tillson/git-hound#21]
![image](https://user-images.githubusercontent.com/45327979/82124577-c2befc00-97c1-11ea-9a4c-4c5ef2042f3b.png)

![image](https://user-images.githubusercontent.com/45327979/82124584-cc486400-97c1-11ea-995f-5c37840735e3.png)
 
How to config my kali . 
anyone can help me for this error

**Comment by tamjid1971** [comment]
![image](https://user-images.githubusercontent.com/45327979/82125196-33681780-97c6-11ea-91a5-ca48b3a5fb0e.png)
My config.yml is

**Comment by tillson** [comment]
Hey @tamjid1971,
It looks like you're trying to run the configuration file instead of the GitHound core program. When you write ./ in front of a filename, the shell interprets it as trying to run it. Try doing ./git-hound instead (in the same folder) Was there something in the documentation that made that unclear?
Your config.yml contents look right, however

**Comment by tamjid1971** [comment]
hey @tillson , not fix 
![image](https://user-images.githubusercontent.com/45327979/82126125-7331fd80-97cc-11ea-9be2-8c170b2cd65f.png)

**Comment by tillson** [comment]
Did you clone the repo or did you download from releases? Run ‘ls’ on the directory

**Comment by tamjid1971** [comment]
![image](https://user-images.githubusercontent.com/45327979/82127368-d3c53880-97d4-11ea-8b53-bcb12bd8524a.png)

I'm trying both methods but not work for me ....

**Comment by tillson** [comment]
I'm going to release a video on this soon. You're very close: There is a file inside your current directory called `git-hound`. If you use command `file git-hound`, it should say something like "executable". This is the file you need to run. You can run the file with `echo "test.com" | ./git-hound`.

**Comment by pager5Cx415Cx415Cx69** [comment]
@tamjid1971 Remove all the previous files. Then get wget to download from the Release source. Then unzip tar. You find the bash executable files. No need to execute config files because thats not the bash files. I guess firstly you clone the repo in repo their is no bash file. So easy would be (wget) the tar not (go get).
