### ISSUE TITLE
dial tcp 0.0.0.0:443: connect: connection refused

### ISSUE THREAD

**Issue by maerbuchicao** [tillson/git-hound#26]
![image](https://user-images.githubusercontent.com/61037744/82527590-67965c00-9b69-11ea-930c-748bd66740aa.png)

**Comment by Muhammed127** [comment]
I have the same problem

**Comment by tillson** [comment]
A few questions for the two of you:
1. Are you using the build from the Releases tab, or are you building from the master branch?
2. Are you using a VPN?

This is an interesting issue as it looks like it's being caused by `raw.githubusercontent.com`'s DNS being mapped to 0.0.0.0 (your machine). Maybe it's a form of rate-limiting from GitHub?
